server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080 #Sentinel dashboard端口
        port: 8719  # sentinel端口，默认8719，若被占用依次+1进行扫描
    gateway:
      discovery:
        locator:
          enabled: true     # 开启从注册中心动态创建路由的功能，利用微服务名进行路由(负载均衡)
      # 路由
      routes:
        #路由的ID，没有固定规则但要求唯一，一般定为服务名
        - id: provider
          # 格式为 lb://应用注册服务名：网关会选择服务名的各个服务实例进行路由
          uri: lb://provider
          # 断言
          predicates:
            # 断言路径相匹配的进行路由,是路由到的那个服务之前要加上的的url前缀
            - Path=/provider/**
            #- After=2020-07-20T11:29:45.121+08:00[Asia/Shanghai] # 规定访问时间范围
            #- Cookie=username,cky  # 带cookie访问

        - id: provider2
          uri: lb://provider2
          predicates:
            - Path=/provider2/**

        - id: consumer
          uri: lb://consumer
          predicates:
            - Path=/consumer/**

logging:
  level:
    root: info
    org.springframework: info

management:
  endpoints:
    web:
      exposure:
        include: '*'