server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true     # 开启从注册中心动态创建路由的功能，利用微服务名进行路由(负载均衡)
      # 路由
      routes:
        - id: provider     #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   # 匹配后提供服务l的路由地址
          uri: lb://provider  # 格式为 lb://应用注册服务名：网关会选择服务名的各个服务实例进行路由
          # 断言
          predicates:
            - Path=/provider/**         # 断言，路径相匹配的进行路由
            - After=2020-07-20T11:29:45.121+08:00[Asia/Shanghai]
            #- Cookie=username,cky  # 带cookie访问

        - id: consumer #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8002 #匹配后提供服务的路由地址
          uri: lb://consumer      #
          predicates:
            - Path=/consumer/**         # 断言，路径相匹配的进行路由
            - After=2020-07-20T11:29:45.121+08:00[Asia/Shanghai]

            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
logging:
  level:
    root: info
    org.springframework: info
